apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"testApp"},"name":"test","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"testApp"}},"template":{"metadata":{"labels":{"app":"testApp"}},"spec":{"containers":[{"image":"gcr.io/teak-perigee-229014/test","name":"test-container"}]}}}}
  creationTimestamp: "2019-12-16T09:48:07Z"
  generation: 2
  labels:
    app: testApp
  name: test
  namespace: default
  resourceVersion: "49957"
  selfLink: /apis/apps/v1/namespaces/default/deployments/test
  uid: 29eb8ed4-1fe9-11ea-8eca-42010a8c006b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: testApp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: testApp
    spec:
      containers:
      - image: gcr.io/teak-perigee-229014/test
        imagePullPolicy: IfNotPresent
        name: test
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
