apiVersion: apps/v1
kind: LoadBalancer
metadata:
  name: test-service-node-new
  labels:
    app: test-service-node-new
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: test-node
